#!/usr/bin/env python3
"""
Script to reinitialize the database with sample products.
"""
import sys
import sqlite3
sys.path.insert(0, '/Users/spidey./Desktop/Daily Drop')

from config import Config

# Create fresh database with tables
conn = sqlite3.connect(Config.DATABASE_PATH)
cursor = conn.cursor()
conn.row_factory = sqlite3.Row

# Create products table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS products (
        product_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        price REAL NOT NULL,
        category TEXT NOT NULL,
        image_path TEXT NOT NULL,
        description TEXT
    )
''')
conn.commit()

# Now populate sample products
sample_products = [
    ('Band aid', 45, 'personal care', '/static/personal care/Band aid.jpeg'),
    ('Dove soap', 50, 'personal care', '/static/personal care/Dove soap.jpeg'),
    ('Dove body wash', 80, 'personal care', '/static/personal care/Dove bodywash.jpeg'),
    ('Face massager', 30, 'personal care', '/static/personal care/face massager.jpeg'),
    ('Facemask', 100, 'personal care', '/static/personal care/facemask.jpeg'),
    ('Face rollon', 100, 'personal care', '/static/personal care/face rollon.jpeg'),
    ('Foot peal mask', 100, 'personal care', '/static/personal care/Foot peal mask.jpeg'),
    ('Garnier wipes', 100, 'personal care', '/static/personal care/Garnier wipes.jpeg'),
    ('Garnier cleansing', 100, 'personal care', '/static/personal care/Garnier cleansing.jpeg'),
    ('simple facewash', 50, 'personal care', '/static/personal care/simple facewash.jpeg'),
    ('Ponds powder', 50, 'personal care', '/static/personal care/Ponds powder.jpeg'),
    ('Dove room fresh', 250, 'personal care', '/static/personal care/Dove room fresh.jpeg'),
    ('Dove spray', 150, 'personal care', '/static/personal care/Dove spray.jpeg'),
    ('Whisper', 60, 'personal care', '/static/personal care/Whisper.jpeg'),
    ('Nivea set', 200, 'personal care', '/static/personal care/Nivea set.jpeg'),
    ('Tooth.brush', 15, 'personal care', '/static/personal care/Tooth.brush.jpeg'),
    ('Colgate', 70, 'personal care', '/static/personal care/Colgate.jpeg'),
    ('Colgate toothpast', 70, 'personal care', '/static/personal care/Colgate toothpast.jpeg'),
    ('Vaseline', 30, 'personal care', '/static/personal care/Vaseline.jpeg'),
    ('Vaseline jelly', 30, 'personal care', '/static/personal care/Vaseline jelly.jpeg'),
    ('Venus razor', 30, 'personal care', '/static/personal care/Venus razor.jpeg'),
    ('Venus razor', 50, 'personal care', '/static/personal care/Venus razor.jpeg'),
    ('Ponds sunscreen', 200, 'personal care', '/static/personal care/Ponds sunscreen.jpeg'),
    ('Pantene E', 200, 'personal care', '/static/personal care/Pantene E.jpeg'),
    ('Ponds 35+', 150, 'personal care', '/static/personal care/Ponds 35+.jpeg'),
    ('Lotus', 200, 'personal care', '/static/personal care/Lotus.jpeg'),
    ('Lotus whitecream', 100, 'personal care', '/static/personal care/Lotus whitecream.jpeg'),
    ('Mac primer', 200, 'personal care', '/static/personal care/Mac primer.jpeg'),
    ('Lakme primer', 150, 'personal care', '/static/personal care/Lakme primer.jpeg'),
    ('Lakme sunscreen', 300, 'personal care', '/static/personal care/Lakme sunscreen.jpeg'),
    ('Lakme 9to5', 300, 'personal care', '/static/personal care/Lakme 9to5.jpeg'),
    ('Lavender mask', 200, 'personal care', '/static/personal care/lavender mask.jpeg'),
    ('lorial kajal', 200, 'personal care', '/static/personal care/lorial kajal.jpeg'),
    ('Castor oil', 150, 'personal care', '/static/personal care/Castor oil.jpeg'),
    ('Mac Foundation', 500, 'personal care', '/static/personal care/Mac Foundation.jpeg'),
    ('Moisturizer', 120, 'personal care', '/static/personal care/moisturizer.jpeg'),
    ('Tomato', 50, 'FruitsandVegetables', '/static/FruitsandVegetables/Tomato.jpg'),
    ('Brinjal', 50, 'FruitsandVegetables', '/static/FruitsandVegetables/Brinjal.jpeg'),
    ('Apples', 70, 'FruitsandVegetables', '/static/FruitsandVegetables/Apples.jpeg'),
    ('Capsicum', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Capsicum.jpeg'),
    ('Fenugreek', 70, 'FruitsandVegetables', '/static/FruitsandVegetables/fenugreek.jpeg'),
    ('Cauliflower', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Cauliflower.jpeg'),
    ('Cucumber', 50, 'FruitsandVegetables', '/static/FruitsandVegetables/Cocumber.jpeg'),
    ('Cabbages', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/cabbages.jpeg'),
    ('Coconut', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Coconut.jpeg'),
    ('Corn', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Corn.jpeg'),
    ('Dragon fruit', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Dragon fruit.jpeg'),
    ('Ladies finger', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Ladies finger.jpeg'),
    ('Brocolli', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Coriender leafs.jpeg'),
    ('Pineapple', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/Pineapple.jpeg'),
    ('Papaya', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Papaya.jpeg'),
    ('Bananas', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Bananas.jpeg'),
    ('Black grapes', 70, 'FruitsandVegetables', '/static/FruitsandVegetables/Black grapes.jpeg'),
    ('Raw mangoes', 70, 'FruitsandVegetables', '/static/FruitsandVegetables/Raw mangoes.jpeg'),
    ('Passion fruit', 70, 'FruitsandVegetables', '/static/FruitsandVegetables/Passion fruit.jpeg'),
    ('Kiwi', 100, 'FruitsandVegetables', '/static/FruitsandVegetables/Kiwi.jpeg'),
    ('Carombola', 100, 'FruitsandVegetables', '/static/FruitsandVegetables/carombola.jpeg'),
    ('Green apple', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Green apple.jpeg'),
    ('Pomegranate', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Promogranate.jpeg'),
    ('Watermelon', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Watermelon.jpeg'),
    ('Musk melon', 40, 'FruitsandVegetables', '/static/FruitsandVegetables/Musk melon.jpeg'),
    ('Butter head lettuce', 60, 'FruitsandVegetables', '/static/FruitsandVegetables/butter head lettuce.jpeg'),
    ('Amul lassi', 20, 'Dairy and breakfast', '/static/Dairy and breakfast/Amul lassi.jpeg'),
    ('Milk', 20, 'Dairy and breakfast', '/static/Dairy and breakfast/milk.jpg'),
    ('egg', 100, 'Dairy and breakfast', '/static/Dairy and breakfast/egg.jpg'),
    ('Badam drink milk', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Badam drink milk.jpeg'),
    ('Bread', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/Bread.jpeg'),
    ('Brown bread', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/Brown bread.jpeg'),
    ('Burger bun', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/Burger bun.jpeg'),
    ('Blueberry cinnamon flax', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Blueberry cinnamon flax.jpeg'),
    ('Butter', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/Butter.jpeg'),
    ('Cheese', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/Cheese.jpeg'),
    ('Cheese slice', 70, 'Dairy and breakfast', '/static/Dairy and breakfast/Cheese slice.jpeg'),
    ('Coca cola tin', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Coca cola tin.jpeg'),
    ('Choco krispis', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Choco krispis.jpeg'),
    ('Coco pops', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Coco pops.jpeg'),
    ('COCONUT MILK', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/COCONUT MILK.jpeg'),
    ('Cocopops chocos', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Cocopops chocos.jpeg'),
    ('Dabur honey', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Dabur honey.jpeg'),
    ('Eno', 10, 'Dairy and breakfast', '/static/Dairy and breakfast/Eno.jpeg'),
    ('Ghee', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/Ghee.jpeg'),
    ('Govind lassi', 40, 'Dairy and breakfast', '/static/Dairy and breakfast/govind lassi.jpeg'),
    ('Gulab jamun', 75, 'Dairy and breakfast', '/static/Dairy and breakfast/Gulab jamun.jpeg'),
    ('Honey', 25, 'Dairy and breakfast', '/static/Dairy and breakfast/Honey.jpeg'),
    ('Jam', 25, 'Dairy and breakfast', '/static/Dairy and breakfast/Jam.jpeg'),
    ('Kissan jam', 25, 'Dairy and breakfast', '/static/Dairy and breakfast/Kissan jam.jpeg'),
    ('Red label', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/tea.jpg'),
    ('Horlicks', 55, 'Dairy and breakfast', '/static/Dairy and breakfast/Horlicks.jpeg'),
    ('Mentos', 10, 'Dairy and breakfast', '/static/Dairy and breakfast/Mentos.jpeg'),
    ('Nutella', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Nutella.jpeg'),
    ('Milkmade', 55, 'Dairy and breakfast', '/static/Dairy and breakfast/Milkmade.jpeg'),
    ('Nescafe', 25, 'Dairy and breakfast', '/static/Dairy and breakfast/Nescafe.jpeg'),
    ('Nut butter', 25, 'Dairy and breakfast', '/static/Dairy and breakfast/Nut butter.jpeg'),
    ('Oatmeal', 75, 'Dairy and breakfast', '/static/Dairy and breakfast/Oatmeal.jpeg'),
    ('Sweet yogurt', 75, 'Dairy and breakfast', '/static/Dairy and breakfast/Sweet yogurt.jpeg'),
    ('Soup', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/soap.jpeg'),
    ('Yippee', 50, 'Dairy and breakfast', '/static/Dairy and breakfast/yippe.jpeg'),
    ('Rava dosa', 100, 'Dairy and breakfast', '/static/Dairy and breakfast/Rava dosa.jpeg'),
    ('Quaker oat', 80, 'Dairy and breakfast', '/static/Dairy and breakfast/Quaker oat.jpeg'),
    ('Maggie', 5, 'Dairy and breakfast', '/static/Dairy and breakfast/Maggie.jpeg'),
    ('Naturalla', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Naturalla.jpeg'),
    ('Patanjali jam', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Patanjali jam.jpeg'),
    ('Mozzarellla cheese', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Mozzarellla cheese.jpeg'),
    ('Bournvita', 100, 'Dairy and breakfast', '/static/Dairy and breakfast/Bournvita.jpeg'),
    ('Peanuts smooth', 30, 'Dairy and breakfast', '/static/Dairy and breakfast/Peanuts smooth.jpeg'),
    ('Peanut butter', 70, 'Dairy and breakfast', '/static/Dairy and breakfast/Peanut butter.jpeg'),
    ('Kitkat', 20, 'Snacks and Beverages', '/static/Snacks/Kitkat.jpeg'),
    ('Kurkure', 20, 'Snacks and Beverages', '/static/Snacks/Kurkure.jpeg'),
    ('Oreo cone', 25, 'Snacks and Beverages', '/static/Snacks/Oreo cone.jpeg'),
    ('Bounty', 25, 'Snacks and Beverages', '/static/Snacks/Bounty.jpeg'),
    ('Cheetos', 30, 'Snacks and Beverages', '/static/Snacks/Cheetos.jpeg'),
    ('Chamallows', 30, 'Snacks and Beverages', '/static/Snacks/Chamallows.jpeg'),
    ('Coca cola tin', 40, 'Snacks and Beverages', '/static/Snacks/Coca cola tin.jpeg'),
    ('Cookie', 40, 'Snacks and Beverages', '/static/Snacks/Cookie.jpg'),
    ('Croissant', 30, 'Snacks and Beverages', '/static/Snacks/Croissant.jpeg'),
    ('Fanta', 50, 'Snacks and Beverages', '/static/Snacks/Fanta.jpeg'),
    ('Fanta tin', 50, 'Snacks and Beverages', '/static/Snacks/Fanta tin.jpeg'),
    ('Hersheys', 40, 'Snacks and Beverages', '/static/Snacks/Hersheys.jpeg'),
    ('kinder joy', 50, 'Snacks and Beverages', '/static/Snacks/kinder joy.jpeg'),
    ('Kitkat cone', 50, 'Snacks and Beverages', '/static/Snacks/Kitkat cone.jpeg'),
    ('Lassi', 30, 'Snacks and Beverages', '/static/Snacks/Lassi.jpeg'),
    ('Lays combo', 70, 'Snacks and Beverages', '/static/Snacks/Lays combo.jpeg'),
    ('Lays salt', 20, 'Snacks and Beverages', '/static/Snacks/Lays salt.jpeg'),
    ('Lychee lassi', 20, 'Snacks and Beverages', '/static/Snacks/Lychee lassi.jpeg'),
    ('Madangles', 25, 'Snacks and Beverages', '/static/Snacks/Madangles.jpeg'),
    ('MARIEGOLD', 25, 'Snacks and Beverages', '/static/Snacks/MARIEGOLD.jpeg'),
    ('Mentos', 10, 'Snacks and Beverages', '/static/Snacks/Mentos.jpeg'),
    ('Nutella', 30, 'Snacks and Beverages', '/static/Snacks/Nutella.jpeg'),
    ('Oreo bites', 15, 'Snacks and Beverages', '/static/Snacks/Oreo bites.jpeg'),
    ('Oreo icecream', 60, 'Snacks and Beverages', '/static/Snacks/Oreo icecream.jpeg'),
    ('PARLEG', 10, 'Snacks and Beverages', '/static/Snacks/PARLEG.jpeg'),
    ('Pepsi', 25, 'Snacks and Beverages', '/static/Snacks/Pepsi.jpeg'),
    ('Pepsi tin', 25, 'Snacks and Beverages', '/static/Snacks/Pepsi tin.jpeg'),
    ('Sprite', 25, 'Snacks and Beverages', '/static/Snacks/Sprite.jpeg'),
    ('Sprite lemon', 25, 'Snacks and Beverages', '/static/Snacks/Sprite lemon.jpeg'),
    ('Sting', 25, 'Snacks and Beverages', '/static/Snacks/Sting.jpeg'),
    ('Peanuts', 100, 'Snacks and Beverages', '/static/Snacks/Peanuts.jpeg'),
    ('M and M', 20, 'Snacks and Beverages', '/static/Snacks/M nd M.jpeg'),
    ('Duplo chocnut', 20, 'Snacks and Beverages', '/static/Snacks/Duplo chocnut.jpeg'),
    ('Dove kit', 150, 'Baby Care', '/static/Baby Care/Dove kit.jpeg'),
    ('Huggies', 200, 'Baby Care', '/static/Baby Care/Huggies.jpeg'),
    ('Huggies wipes', 175, 'Baby Care', '/static/Baby Care/Huggies wipes.jpeg'),
    ('Johnsons kit', 300, 'Baby Care', '/static/Baby Care/Johnsons kit.jpeg'),
    ('Johnsons powder', 250, 'Baby Care', '/static/Baby Care/Johnsons powder.jpeg'),
    ('Johnsons Shampoo', 200, 'Baby Care', '/static/Baby Care/Johnsons Shampoo.jpeg'),
    ('Johnsons shampoos', 400, 'Baby Care', '/static/Baby Care/Johnsons shampoos.jpeg'),
    ('Mamy poko pants', 200, 'Baby Care', '/static/Baby Care/Mamy poko pants.jpeg'),
    ('Mamy poko pants l', 200, 'Baby Care', '/static/Baby Care/Mamy poko pants l.jpeg'),
    ('Mamy poko pants s4', 200, 'Baby Care', '/static/Baby Care/Mamy poko pants s4.jpeg'),
    ('Pampers', 200, 'Baby Care', '/static/Baby Care/Pampers.jpeg'),
    ('Pampers wipes', 200, 'Baby Care', '/static/Baby Care/Pampers wipes.jpeg'),
    ('Baby biscuits', 75, 'Baby Care', '/static/Baby Care/Baby biscuits.jpeg'),
    ('Nestle cereales', 300, 'Baby Care', '/static/Baby Care/Nestle cereales.jpeg'),
    ('Jeera powder', 250, 'Grocery', '/static/Grocery/Jeera powder.jpeg'),
    ('Kasuri methi', 250, 'Grocery', '/static/Grocery/Kasuri methi.jpeg'),
    ('Green moong', 250, 'Grocery', '/static/Grocery/Green moong.jpeg'),
    ('Clove', 70, 'Grocery', '/static/Grocery/Clove.jpeg'),
    ('Chakki atta', 300, 'Grocery', '/static/Grocery/Chakki atta.jpeg'),
    ('Ragi flour', 300, 'Grocery', '/static/Grocery/Ragi flour.jpeg'),
    ('Jasmine rice', 300, 'Grocery', '/static/Grocery/Jasmine rice.jpeg'),
    ('Basmathi rice', 300, 'Grocery', '/static/Grocery/Basmathi rice.jpeg'),
    ('Masala vadamix', 250, 'Grocery', '/static/Grocery/Masala vadamix.jpeg'),
    ('Black seeds', 70, 'Grocery', '/static/Grocery/Black seeds.jpeg'),
    ('Mutton masala', 50, 'Grocery', '/static/Grocery/Mutton masala.jpeg'),
    ('Sugar', 150, 'Grocery', '/static/Grocery/Sugar.jpeg'),
    ('Salt', 150, 'Grocery', '/static/Grocery/Salt.jpeg'),
    ('Aashirvad salt', 150, 'Grocery', '/static/Grocery/Aashirvad salt.jpeg'),
    ('Kasoori methi', 150, 'Grocery', '/static/Grocery/Kasoori methi.jpeg'),
    ('Green cardomom', 250, 'Grocery', '/static/Grocery/Green cardomom.jpeg'),
    ('Cardomom', 250, 'Grocery', '/static/Grocery/Cardomom.jpeg'),
    ('Cardomom pods', 250, 'Grocery', '/static/Grocery/Cardomom pods.jpeg'),
    ('Coriander powder', 250, 'Grocery', '/static/Grocery/Coriander powder.jpeg'),
    ('Besan', 150, 'Grocery', '/static/Grocery/Besan.jpeg'),
    ('Masoor dal', 150, 'Grocery', '/static/Grocery/Masoor dal.jpeg'),
    ('Organic kalonji', 300, 'Grocery', '/static/Grocery/Organic kalonji.jpeg'),
    ('Cumin ground 180g', 300, 'Grocery', '/static/Grocery/Cumin ground 180g.jpeg'),
    ('Moong dal', 300, 'Grocery', '/static/Grocery/Moong dal.jpeg'),
    ('Cardomom seeds', 170, 'Grocery', '/static/Grocery/Cardomom seeds.jpeg'),
    ('Cardomom seeds 50g', 80, 'Grocery', '/static/Grocery/Cardomom seeds 50g.jpeg'),
    ('Atta', 280, 'Grocery', '/static/Grocery/Atta.jpeg'),
    ('Ground cumin', 150, 'Grocery', '/static/Grocery/Ground cumin.jpeg'),
    ('Biryani masala', 150, 'Grocery', '/static/Grocery/Biryani masala.jpeg'),
    ('Sticky rice', 350, 'Grocery', '/static/Grocery/Sticky rice.jpeg'),
    ('Sweet rice', 200, 'Grocery', '/static/Grocery/Sweet rice.jpeg'),
    ('Toor dal', 200, 'Grocery', '/static/Grocery/Toor dal.jpeg'),
    ('Tata chanadal', 200, 'Grocery', '/static/Grocery/Tata chanadal.jpeg'),
    ('Fish curry masala', 200, 'Grocery', '/static/Grocery/Fish curry masala.jpeg'),
    ('Dal tadka', 200, 'Grocery', '/static/Grocery/Dal tadka.jpeg'),
    ('Garam masala', 60, 'Grocery', '/static/Grocery/Garam masala.jpeg'),
    ('organic moong dal', 100, 'Grocery', '/static/Grocery/organic moong dal.jpeg'),
    ('Pickle', 100, 'Grocery', '/static/Grocery/Pickle.jpeg'),
    ('Pizza sause', 100, 'Grocery', '/static/Grocery/Pizza sause.jpeg'),
    ('Rice', 300, 'Grocery', '/static/Grocery/Rice.jpeg'),
    ('Natco rice flour', 300, 'Grocery', '/static/Grocery/Natco rice flour.jpeg'),
    ('Urad dal', 100, 'Grocery', '/static/Grocery/Urad dal.jpeg'),
    ('Multigrain atta', 400, 'Grocery', '/static/Grocery/Multigrain atta.jpeg'),
    ('Aer', 120, 'House Hold', '/static/household/Aer.jpeg'),
    ('Air fresher', 120, 'House Hold', '/static/household/Air fresher.jpeg'),
    ('Air mist', 100, 'House Hold', '/static/household/Air mist.jpeg'),
    ('Air wick', 100, 'House Hold', '/static/household/Air wick.jpeg'),
    ('aireal', 200, 'House Hold', '/static/household/aireal.jpeg'),
    ('Attack', 200, 'House Hold', '/static/household/Attack.jpeg'),
    ('Clip', 60, 'House Hold', '/static/household/Clip.jpeg'),
    ('clorox', 60, 'House Hold', '/static/household/clorox.jpeg'),
    ('dettol', 50, 'House Hold', '/static/household/dettol.jpeg'),
    ('dishwasher', 100, 'House Hold', '/static/household/dishwasher.jpeg'),
    ('downy', 100, 'House Hold', '/static/household/downy.jpeg'),
    ('Downy cleaner', 100, 'House Hold', '/static/household/Downy cleaner.jpeg'),
    ('dust pan', 80, 'House Hold', '/static/household/dust pan.jpeg'),
    ('dustbin', 80, 'House Hold', '/static/household/dustbin.jpeg'),
    ('dustbin cover', 80, 'House Hold', '/static/household/dustbin cover.jpeg'),
    ('Febreze', 80, 'House Hold', '/static/household/Febreze.jpeg'),
    ('Fairy', 90, 'House Hold', '/static/household/Fairy.jpeg'),
    ('Glade', 100, 'House Hold', '/static/household/Glade.jpeg'),
    ('Glade spray', 100, 'House Hold', '/static/household/Glade spray.jpeg'),
    ('Glade air', 100, 'House Hold', '/static/household/Glade air.jpeg'),
    ('Glat set', 100, 'House Hold', '/static/household/Glat set.jpeg'),
    ('Harpic', 300, 'House Hold', '/static/household/Harpic.jpeg'),
    ('Lenor', 150, 'House Hold', '/static/household/Lenor.jpeg'),
    ('mop', 150, 'House Hold', '/static/household/mop.jpeg'),
    ('Pril', 150, 'House Hold', '/static/household/Pril.jpeg'),
    ('Room spray', 230, 'House Hold', '/static/household/Room spray.jpeg'),
    ('Softouch', 250, 'House Hold', '/static/household/Softouch.jpeg'),
    ('sponge', 400, 'House Hold', '/static/household/sponge.jpeg'),
    ('spray bottles', 400, 'House Hold', '/static/household/spray bottles.jpeg'),
    ('Tide', 240, 'House Hold', '/static/household/tide.jpeg'),
    ('Tub', 270, 'House Hold', '/static/household/tub.jpeg'),
    ('Vanish', 300, 'House Hold', '/static/household/Vanish.jpeg'),
    ('Apron', 275, 'Home and Kitchen', '/static/kitchen/Apron.jpeg'),
    ('Boul set', 320, 'Home and Kitchen', '/static/kitchen/Boul set.jpeg'),
    ('Chopper', 250, 'Home and Kitchen', '/static/kitchen/Chopper.jpeg'),
    ('Container', 200, 'Home and Kitchen', '/static/kitchen/Container.jpeg'),
    ('Crocy holder', 200, 'Home and Kitchen', '/static/kitchen/Crocy holder.jpeg'),
    ('Cutter', 200, 'Home and Kitchen', '/static/kitchen/Cutter.jpeg'),
    ('Cutting board', 200, 'Home and Kitchen', '/static/kitchen/Cutting board.jpeg'),
    ('Glass set', 150, 'Home and Kitchen', '/static/kitchen/Glass set.jpeg'),
    ('Grain container', 150, 'Home and Kitchen', '/static/kitchen/Grain container.jpeg'),
    ('Jar', 150, 'Home and Kitchen', '/static/kitchen/Jar.jpeg'),
    ('Knife holder', 150, 'Home and Kitchen', '/static/kitchen/Knife holder.jpeg'),
    ('Plate set', 400, 'Home and Kitchen', '/static/kitchen/Plate set.jpeg'),
    ('Round pan', 400, 'Home and Kitchen', '/static/kitchen/Round pan.jpeg'),
    ('Spice holder', 400, 'Home and Kitchen', '/static/kitchen/Spice holder.jpeg'),
]

try:
    cursor.executemany('''
        INSERT INTO products (name, price, category, image_path)
        VALUES (?, ?, ?, ?)
    ''', sample_products)
    conn.commit()
    print(f"✓ Database reinitialized successfully!")
    print(f"✓ Inserted {len(sample_products)} products")
except Exception as e:
    print(f"✗ Error: {e}")
    sys.exit(1)
finally:
    conn.close()
